/*
 *
 *
 *
 * USERS
 *
 *
 *
 */
export const users = [
  {
    firstName: "Bogart",
    lastName: "Lotze",
    name: "Bogart Lotze",
    email: "blotze0@company.com",
  },
  {
    firstName: "Lianne",
    lastName: "Whilder",
    name: "Lianne Whilder",
    email: "lwhilder1@company.com",
  },
  {
    firstName: "Caryl",
    lastName: "Whitmarsh",
    name: "Caryl Whitmarsh",
    email: "cwhitmarsh2@company.com",
  },
  {
    firstName: "Barbie",
    lastName: "Snibson",
    name: "Barbie Snibson",
    email: "bsnibson3@company.com",
  },
  {
    firstName: "Alexis",
    lastName: "Tolcher",
    name: "Alexis Tolcher",
    email: "atolcher4@company.com",
  },
  {
    firstName: "Toiboid",
    lastName: "Tysall",
    name: "Toiboid Tysall",
    email: "ttysall5@company.com",
  },
  {
    firstName: "Odella",
    lastName: "Rookes",
    name: "Odella Rookes",
    email: "orookes6@company.com",
  },
  {
    firstName: "Zonnya",
    lastName: "Parris",
    name: "Zonnya Parris",
    email: "zparris7@company.com",
  },
  {
    firstName: "Ephraim",
    lastName: "Elecum",
    name: "Ephraim Elecum",
    email: "eelecum8@company.com",
  },
  {
    firstName: "Zorine",
    lastName: "Dellow",
    name: "Zorine Dellow",
    email: "zdellow9@company.com",
  },
  {
    firstName: "Jorrie",
    lastName: "Featherston",
    name: "Jorrie Featherston",
    email: "jfeatherstona@company.com",
  },
  {
    firstName: "Cathrine",
    lastName: "Armfield",
    name: "Cathrine Armfield",
    email: "carmfieldb@company.com",
  },
  {
    firstName: "Mohandas",
    lastName: "Kernoghan",
    name: "Mohandas Kernoghan",
    email: "mkernoghanc@company.com",
  },
  {
    firstName: "Dena",
    lastName: "Kingzeth",
    name: "Dena Kingzeth",
    email: "dkingzethd@company.com",
  },
  {
    firstName: "Dannie",
    lastName: "Arnaldo",
    name: "Dannie Arnaldo",
    email: "darnaldoe@company.com",
  },
  {
    firstName: "Palm",
    lastName: "Kenryd",
    name: "Palm Kenryd",
    email: "pkenrydf@company.com",
  },
  {
    firstName: "Vaughan",
    lastName: "Gopsall",
    name: "Vaughan Gopsall",
    email: "vgopsallg@company.com",
  },
  {
    firstName: "Riannon",
    lastName: "Raubenheimer",
    name: "Riannon Raubenheimer",
    email: "rraubenheimerh@company.com",
  },
  {
    firstName: "Vittorio",
    lastName: "Bente",
    name: "Vittorio Bente",
    email: "vbentei@company.com",
  },
  {
    firstName: "Morlee",
    lastName: "Brandenburg",
    name: "Morlee Brandenburg",
    email: "mbrandenburgj@company.com",
  },
  {
    firstName: "Felisha",
    lastName: "Bogace",
    name: "Felisha Bogace",
    email: "fbogacek@company.com",
  },
  {
    firstName: "Beverly",
    lastName: "Hadland",
    name: "Beverly Hadland",
    email: "bhadlandl@company.com",
  },
  {
    firstName: "Foss",
    lastName: "McLagain",
    name: "Foss McLagain",
    email: "fmclagainm@company.com",
  },
  {
    firstName: "Veronica",
    lastName: "Tolchard",
    name: "Veronica Tolchard",
    email: "vtolchardn@company.com",
  },
  {
    firstName: "Dannie",
    lastName: "Summergill",
    name: "Dannie Summergill",
    email: "dsummergillo@company.com",
  },
];

/*
 *
 *
 *
 * ASSETS
 *
 *
 *
 */
export const assets = [
  {
    name: "Dancing Bears Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXVSX13",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY2H63",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 3",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3WFZLP2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 4",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXVTX13",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 5",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XJXXN02",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 6",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY4H63",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 7",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2334LH2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes:
      "Brian had problems with Office 365 - J&J did a clean install - seems OK now)",
  },
  {
    name: "Dancing Bears Desktop 8",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "1WY6M82",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 9",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23M3LH2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "hard drive replace 10-10-19",
  },
  {
    name: "Dancing Bears Desktop 10",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY1H63",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 11",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X303H02",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 12",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X39N032",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DF9YHV2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "(was in ABQ - now in SF)",
  },
  {
    name: "Dancing Bears Desktop 14",
    type: "DESKTOP",
    brand: "Apple",
    serialNumber: "4JMMJX1",
    status: "available",
    condition: "VERY_POOR",
    conditionNotes:
      "Old but serviceable with upgrades. Video Station. Has Final Cut Pro installed.",
  },
  {
    name: "Dancing Bears Desktop 15",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23XZXH2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 16",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23FYXH2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 17",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23HYXH2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 18",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXXXXW1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 19",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JDXFTW1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 20",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "8LNW2Y1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 21",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2Z0TP32",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 22",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY3H63",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "XSXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 2",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3T3F3X3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3TXSRX2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "1JJXTX2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "JHO2ZM2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XXJXTX2",
    status: "available",
    condition: "WORN",
    conditionNotes:
      "Dropped and chipped case 5/22, but seems to be working well. Taped case",
  },
  {
    name: "Dancing Bears Laptop 8",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XT3F383",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 9",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "HDXRXF2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 10",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "DXFP0N2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 11",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "H23XNF2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 12",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "X42LNF2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 13",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "9SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 14",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "8SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 15",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "6SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 16",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3ZTNW33",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 17",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XL2NLH2",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 18",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3T3F3X3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 19",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "1SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 20",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "4X9MNF2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes:
      "Dec 21 - upgrade to 16 GB RAM & new battery (was swollen), another new battery 4/12/22",
  },
  {
    name: "Dancing Bears Laptop 21",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "2SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 22",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JPLD4H2",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 23",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "92XH9W1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 24",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3XNMJX1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 25",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XW60LX1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XF9N032",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XD8R8Z1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 3",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3WX2MP2",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 4",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "H3XY3X2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 5",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XX13H03",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 6",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DXNTL02",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 7",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3F33H02",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 8",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2FXRYX1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 9",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DF80JV2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 10",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "32S0W02",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 11",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "HX9N032",
    status: "lost",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 12",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "30XTP32",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2ZFWX62",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 14",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X2LPXV1",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 15",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X28WXV1",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 16",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2XXXN02",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "6X2TRX2",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 2",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "1HH93X2",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "4SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JRXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XT3F3X3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 8",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3TDXRP1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 9",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "F830LX1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 10",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "HJ8STX1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
];

/*
 *
 * ASSET ASSIGNMENTS
 *
 */
export const assetAssignments: { [key: string]: string } = {
  "Dancing Bears Desktop 19": "blotze0@company.com",

  "Dancing Bears Desktop 20": "lwhilder1@company.com",

  "Dancing Bears Desktop 21": "cwhitmarsh2@company.com",

  "Dancing Bears Desktop 22": "bsnibson3@company.com",

  "Dancing Bears Laptop 1": "blotze0@company.com",

  "Dancing Bears Laptop 2": "lwhilder1@company.com",

  "Dancing Bears Laptop 3": "cwhitmarsh2@company.com",

  "Dancing Bears Laptop 4": "bsnibson3@company.com",

  "Dancing Bears Laptop 5": "atolcher4@company.com",

  "Dancing Bears Laptop 6": "ttysall5@company.com",

  "Highwater Desktop 1": "blotze0@company.com",
};
