/*
 *
 *
 *
 * USERS
 *
 *
 *
 */
export const users = [];

/*
 *
 *
 *
 * ASSETS
 *
 *
 *
 */
export const assets = [
  {
    name: "Dancing Bears Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXVSX13",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY2H63",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 3",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3WFZLP2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 4",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXVTX13",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 5",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XJXXN02",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 6",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY4H63",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 7",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2334LH2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes:
      "Brian had problems with Office 365 - J&J did a clean install - seems OK now)",
  },
  {
    name: "Dancing Bears Desktop 8",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "1WY6M82",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 9",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23M3LH2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "hard drive replace 10-10-19",
  },
  {
    name: "Dancing Bears Desktop 10",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY1H63",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 11",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X303H02",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 12",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X39N032",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DF9YHV2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "(was in ABQ - now in SF)",
  },
  {
    name: "Dancing Bears Desktop 14",
    type: "DESKTOP",
    brand: "Apple",
    serialNumber: "4JMMJX1",
    status: "assigned",
    condition: "VERY_POOR",
    conditionNotes:
      "Old but serviceable with upgrades. Video Station. Has Final Cut Pro installed.",
  },
  {
    name: "Dancing Bears Desktop 15",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23XZXH2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 16",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23FYXH2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 17",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23HYXH2",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 18",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXXXXW1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 19",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JDXFTW1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 20",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "8LNW2Y1",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 21",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2Z0TP32",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 22",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY3H63",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "XSXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 2",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3T3F3X3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3TXSRX2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "1JJXTX2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "JHO2ZM2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XXJXTX2",
    status: "assigned",
    condition: "WORN",
    conditionNotes:
      "Dropped and chipped case 5/22, but seems to be working well. Taped case",
  },
  {
    name: "Dancing Bears Laptop 8",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XT3F383",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 9",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "HDXRXF2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 10",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "DXFP0N2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 11",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "H23XNF2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 12",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "X42LNF2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 13",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "9SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 14",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "8SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 15",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "6SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 16",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3ZTNW33",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 17",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XL2NLH2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 18",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3T3F3X3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 19",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "1SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 20",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "4X9MNF2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes:
      "Dec 21 - upgrade to 16 GB RAM & new battery (was swollen), another new battery 4/12/22",
  },
  {
    name: "Dancing Bears Laptop 21",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "2SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 22",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JPLD4H2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 23",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "92XH9W1",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 24",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3XNMJX1",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 25",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XW60LX1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XF9N032",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XD8R8Z1",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 3",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3WX2MP2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 4",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "H3XY3X2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 5",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XX13H03",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 6",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DXNTL02",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 7",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3F33H02",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 8",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2FXRYX1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 9",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DF80JV2",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 10",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "32S0W02",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 11",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "HX9N032",
    status: "lost",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 12",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "30XTP32",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2ZFWX62",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 14",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X2LPXV1",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 15",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X28WXV1",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 16",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2XXXN02",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "6X2TRX2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 2",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "1HH93X2",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "4SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JRXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XT3F3X3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 8",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3TDXRP1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 9",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "F830LX1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 10",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "HJ8STX1",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
];
