import Head from "next/head";

type DefaultLayoutProps = { children: React.ReactNode };

const DefaultLayout = ({ children }: DefaultLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-green-400">{children}</main>
    </>
  );
};

export default DefaultLayout;
