/*
 *
 *
 *
 * ASSETS
 *
 *
 *
 */
export default [
  {
    name: "Dancing Bears Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XXVSX13",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY2H63",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 7",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2334LH2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes:
      "Brian had problems with Office 365 - J&J did a clean install - seems OK now)",
  },
  {
    name: "Dancing Bears Desktop 8",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "1WY6M82",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 9",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "23M3LH2",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "hard drive replace 10-10-19",
  },
  {
    name: "Dancing Bears Desktop 10",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "JFY1H63",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 11",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X303H02",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 12",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X39N032",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "DF9YHV2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "(was in ABQ - now in SF)",
  },
  {
    name: "Dancing Bears Desktop 14",
    type: "DESKTOP",
    brand: "Apple",
    serialNumber: "4JMMJX1",
    status: "available",
    condition: "VERY_POOR",
    conditionNotes:
      "Old but serviceable with upgrades. Video Station. Has Final Cut Pro installed.",
  },
  {
    name: "Dancing Bears Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "XSXNXX3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 2",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3T3F3X3",
    status: "assigned",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3TXSRX2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "1JJXTX2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "JHO2ZM2",
    status: "assigned",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XXJXTX2",
    status: "available",
    condition: "WORN",
    conditionNotes:
      "Dropped and chipped case 5/22, but seems to be working well. Taped case",
  },
  {
    name: "Dancing Bears Laptop 21",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "2SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 22",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JPLD4H2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 23",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "92XH9W1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Dancing Bears Laptop 24",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3XNMJX1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 1",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XF9N032",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 2",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "XD8R8Z1",
    status: "available",
    condition: "AVERAGE",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 3",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "3WX2MP2",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },

  {
    name: "Highwater Desktop 13",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2ZFWX62",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 14",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X2LPXV1",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 15",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "X28WXV1",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Desktop 16",
    type: "DESKTOP",
    brand: "Dell",
    serialNumber: "2XXXN02",
    status: "available",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 1",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "6X2TRX2",
    status: "assigned",
    condition: "EXCELLENT",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 2",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "1HH93X2",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 3",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "4SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 4",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "JRXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 5",
    type: "LAPTOP",
    brand: "Apple",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 6",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "3SXNXX3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Laptop 7",
    type: "LAPTOP",
    brand: "Dell",
    serialNumber: "XT3F3X3",
    status: "available",
    condition: "NEW",
    conditionNotes: "",
  },
  {
    name: "Highwater Office Phone 7",
    type: "OFFICE_PHONE",
    brand: "Telnet",
    serialNumber: "XT3F3X3",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Office Phone 8",
    type: "OFFICE_PHONE",
    brand: "Telnet",
    serialNumber: "XT3F3X3",
    status: "assigned",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "Highwater Office Phone 9",
    type: "OFFICE_PHONE",
    brand: "Telnet",
    serialNumber: "XT3F3X3",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
  {
    name: "On the Road Cell Phone",
    type: "CELL_PHONE",
    brand: "Samsung",
    serialNumber: "XT3F3X3",
    status: "available",
    condition: "GOOD",
    conditionNotes: "",
  },
];
